export const pathologyTests = [
  {
    slug: "complete-blood-count-cbc",
    image: "/catalog/pathology/cbc.jpg",
    title: "Complete Blood Count (CBC)",
    short: "A core blood profile covering haemoglobin, red cells, white cells and platelets.",
    sample: "Blood sample",
    preparation: "Fasting is usually not required unless combined with another test.",
    includes: ["Haemoglobin", "RBC and WBC count", "Platelet count", "PCV and indices"],
  },
  {
    slug: "thyroid-profile",
    image: "/catalog/pathology/thyroid.jpg",
    title: "Thyroid Profile",
    short: "TSH, T3 and T4 testing to support assessment of thyroid function.",
    sample: "Blood sample",
    preparation: "Share current thyroid medicines with the collection team.",
    includes: ["TSH", "Total T3", "Total T4", "Report review support"],
  },
  {
    slug: "liver-function-test",
    image: "/catalog/pathology/liver.jpg",
    title: "Liver Function Test (LFT)",
    short: "A comprehensive profile of enzymes, proteins and bilirubin related to liver health.",
    sample: "Blood sample",
    preparation: "Fasting may be advised; confirm while booking.",
    includes: ["Bilirubin", "SGOT and SGPT", "Alkaline phosphatase", "Protein and albumin"],
  },
  {
    slug: "kidney-function-test",
    image: "/catalog/pathology/kidney.jpg",
    title: "Kidney Function Test (KFT)",
    short: "Key renal markers used for kidney-health assessment and ongoing monitoring.",
    sample: "Blood sample",
    preparation: "Hydration and fasting instructions depend on the requested profile.",
    includes: ["Creatinine", "Urea and BUN", "Uric acid", "Electrolytes"],
  },
  {
    slug: "diabetes-profile",
    image: "/catalog/pathology/diabetes.jpg",
    title: "Diabetes Profile",
    short: "Blood sugar and HbA1c testing for screening and longer-term glucose monitoring.",
    sample: "Blood sample",
    preparation: "8-12 hours fasting is needed for fasting glucose profiles.",
    includes: ["Fasting blood sugar", "Post-meal blood sugar", "HbA1c", "Estimated average glucose"],
  },
  {
    slug: "lipid-profile",
    image: "/catalog/pathology/lipid.jpg",
    title: "Lipid Profile",
    short: "Cholesterol and triglyceride measurements supporting cardiovascular risk assessment.",
    sample: "Blood sample",
    preparation: "Fasting may be advised depending on the clinician's request.",
    includes: ["Total cholesterol", "HDL and LDL", "Triglycerides", "VLDL and ratios"],
  },
  {
    slug: "urine-routine",
    image: "/catalog/pathology/urine.jpg",
    title: "Urine Routine & Microscopy",
    short: "Physical, chemical and microscopic urine analysis for common clinical indicators.",
    sample: "Fresh urine sample",
    preparation: "Use a clean collection container and follow collection instructions.",
    includes: ["Sugar and protein", "Pus and epithelial cells", "Crystals", "Physical examination"],
  },
  {
    slug: "vitamin-profile",
    image: "/catalog/pathology/vitamins.jpg",
    title: "Vitamin B12 & Vitamin D",
    short: "Common vitamin-level testing for fatigue, bone health and nutritional assessment.",
    sample: "Blood sample",
    preparation: "Tell the team about supplements currently being taken.",
    includes: ["Vitamin B12", "25-OH Vitamin D", "Deficiency screening", "Report support"],
  },
];

export const organicFoods = [
  { slug: "jaivik-aalu", image: "/catalog/organic/jaivik-aalu.jpg", title: "Jaivik Aalu", category: "Fresh Produce", text: "Naturally grown potatoes selected for everyday family cooking.", points: ["Seasonal availability", "Farm-fresh selection", "Courier enquiry available"] },
  { slug: "jaivik-tamatar", image: "/catalog/organic/jaivik-tamatar.jpg", title: "Jaivik Tamatar", category: "Fresh Produce", text: "Fresh, flavourful organic tomatoes sourced according to the harvest season.", points: ["Naturally grown", "Fresh harvest", "Bulk enquiry available"] },
  { slug: "fresh-aamla", image: "/catalog/organic/fresh-aamla.jpg", title: "Fresh Aamla", category: "Seasonal Wellness", text: "Fresh Indian gooseberry valued in traditional food and wellness routines.", points: ["Seasonal fresh stock", "Whole fruit", "Availability on enquiry"] },
  { slug: "raw-honey", image: "/catalog/organic/raw-honey.jpg", title: "Natural Raw Honey", category: "Natural Pantry", text: "Naturally sourced honey for food and traditional household use.", points: ["Natural sweetness", "Small-batch availability", "Courier enquiry available"] },
  { slug: "seasonal-mangoes", image: "/catalog/organic/seasonal-mangoes.jpg", title: "Seasonal Mangoes", category: "Seasonal Fruit", text: "Carefully selected seasonal mangoes offered during the fresh harvest window.", points: ["Seasonal varieties", "Naturally ripened selection", "Pre-booking enquiry"] },
  { slug: "whole-grains-pulses", image: "/catalog/organic/whole-grains-pulses.jpg", title: "Whole Grains & Pulses", category: "Daily Staples", text: "Wholesome grains and pulses for a simple, balanced everyday kitchen.", points: ["Everyday staples", "Whole-food selection", "Bulk enquiry available"] },
  { slug: "haldi-herbs", image: "/catalog/organic/haldi-herbs.jpg", title: "Fresh Haldi & Herbs", category: "Farm Herbs", text: "Fresh turmeric roots and useful seasonal herbs from nature-led cultivation.", points: ["Fresh turmeric", "Seasonal leafy herbs", "Farm-stock enquiry"] },
  { slug: "organic-combo", image: "/catalog/organic/organic-combo.jpg", title: "Organic Family Combo", category: "Curated Basket", text: "A seasonal mix of available vegetables, fruit, grains and natural pantry products.", points: ["Curated seasonal basket", "Family-friendly selection", "Courier eligibility check"] },
];
