import Link from "next/link";
import { Phone, MapPin } from "lucide-react";
import LandingEnquiryForm from "../../_components/LandingEnquiryForm";
import Banner from "./Banner";

export default function BalpradaAyurvedicHospital() {
  const faqs = [
    {
      q: "Can Ayurveda reduce high creatinine levels?",
      a: "In many cases, supportive Ayurvedic care combined with diet and lifestyle changes may help. Results vary by patient and underlying cause, which is why report-based evaluation is essential.",
    },
    {
      q: "How soon will my creatinine levels improve?",
      a: "This depends on the cause, stage of kidney function, and how consistently the treatment plan is followed. Our physicians give realistic timelines after reviewing your reports.",
    },
    {
      q: "Do I need to stop my current medications during Ayurvedic treatment?",
      a: "No. Ayurvedic supportive care is meant to work alongside your prescribed medications, not replace them.",
    },
    {
      q: "Is high protein intake always the cause of high creatinine?",
      a: "Not always. Diet is one factor, but underlying kidney conditions, dehydration, and other causes must also be evaluated.",
    },
    {
      q: "Will I need repeated blood tests during treatment?",
      a: "Yes, periodic testing is important to track whether your creatinine trend is improving, stable, or needs a change in approach.",
    },
    {
      q: "Can creatinine levels be reduced permanently?",
      a: "This depends on the underlying cause. Some causes are reversible with timely care, while chronic kidney conditions require ongoing, long-term management.",
    },
  ];

  return (
    <main className="bg-white">
      <Banner />

      <section className="px-6 py-16">
        <div className="mx-auto flex max-w-7xl flex-col gap-10 lg:flex-row">
          <div className="order-1 flex-1">
            <div className="mb-12">
              

              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Understanding High Creatinine and Why It Matters
              </h2>

              <p className="mb-4 text-gray-700">
                Creatinine is a waste product generated by muscle metabolism, and its level in the blood is one of the most important markers of how well your kidneys are functioning. At Balprada Ayurvedic Hospital &amp; Research Center, we offer structured Ayurvedic supportive care aimed at helping the body manage and, where possible, reduce elevated creatinine levels — always alongside your ongoing nephrology treatment.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Creatinine is filtered out of the blood by the kidneys and removed through urine</li>
                <li>When kidney function declines, creatinine builds up in the bloodstream, and a blood test shows this as an elevated serum creatinine level</li>
                <li>A rising creatinine level is often one of the earliest measurable signs that kidney function is being affected, even before symptoms appear</li>
                <li>Our approach focuses on supporting the kidneys&apos; natural filtering capacity, reducing the internal toxin load, and slowing further increases where medically appropriate</li>
                <li>Every treatment plan is built around the patient&apos;s actual lab reports, not assumptions — we always ask to see your latest creatinine and GFR values first</li>
                <li>This is supportive care, not a replacement for the nephrology treatment your creatinine levels require</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                What Counts as a Normal or High Creatinine Level
              </h2>

              <p className="mb-4 text-gray-700">
                Understanding the numbers helps patients and families make sense of their reports.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Normal creatinine ranges vary slightly by lab, age, gender, and muscle mass, so your doctor&apos;s reference range should always be the guide</li>
                <li>A gradually rising trend across multiple tests is often more significant than a single reading</li>
                <li>Creatinine is usually assessed alongside GFR (Glomerular Filtration Rate) for a fuller picture of kidney function</li>
                <li>Mildly elevated creatinine may reflect early kidney stress, while significantly high levels usually indicate more advanced kidney impairment</li>
                <li>We always ask patients to bring their most recent and previous reports so we can track the trend, not just a single number</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Common Causes of Elevated Creatinine
              </h2>

              <p className="mb-4 text-gray-700">
                Identifying the underlying cause is essential before designing any supportive treatment plan.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Chronic Kidney Disease at various stages</li>
                <li>Uncontrolled diabetes affecting kidney filtration (diabetic nephropathy)</li>
                <li>Long-standing high blood pressure</li>
                <li>Dehydration, which can temporarily raise creatinine levels</li>
                <li>Certain medications, including long-term or excessive use of painkillers</li>
                <li>Urinary tract obstruction, such as kidney stones</li>
                <li>High-protein diets and intense muscle-building activity, which can mildly influence readings</li>
                <li>Underlying infections or inflammation affecting the kidneys</li>
                <li>Reduced blood flow to the kidneys due to heart or vascular conditions</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Symptoms That May Accompany High Creatinine
              </h2>

              <p className="mb-4 text-gray-700">
                Elevated creatinine itself often has no direct symptoms, but the underlying kidney stress may produce noticeable signs.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Persistent fatigue and low energy</li>
                <li>Swelling in the feet, ankles, or around the eyes</li>
                <li>Reduced appetite or nausea</li>
                <li>Changes in urine output or appearance</li>
                <li>Difficulty concentrating</li>
                <li>Muscle cramps</li>
                <li>Elevated or difficult-to-control blood pressure</li>
                <li>Mild breathlessness in more advanced cases</li>
              </ul>

              <p className="text-gray-700">
                Since high creatinine is usually detected through routine blood work rather than obvious symptoms, regular testing is important for anyone with risk factors such as diabetes or hypertension.
              </p>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                The Ayurvedic Perspective on Elevated Creatinine
              </h2>

              <p className="mb-4 text-gray-700">
                Ayurveda approaches elevated creatinine as a sign of accumulated Ama (toxins) and weakened Agni (digestive fire), which places additional strain on the Mutravaha Srotas (urinary channels) and overall kidney function.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Weak Agni is believed to prevent proper metabolism of waste products, contributing to their buildup in the blood</li>
                <li>Aggravated Apana Vata is associated with reduced efficiency in the body&apos;s natural elimination processes</li>
                <li>The goal of Ayurvedic supportive care is to strengthen digestive fire, reduce Ama accumulation, and support the kidneys&apos; own filtering capacity</li>
                <li>This is achieved gradually, through herbs, diet, and lifestyle changes tailored to the patient&apos;s dosha and current kidney status</li>
                <li>We view creatinine reduction as a process of restoring internal balance, not a quick or guaranteed fix</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Our Approach to Creatinine Reduction Support
              </h2>

              <p className="mb-4 text-gray-700">
                At Balprada Ayurvedic Hospital, every patient with elevated creatinine goes through a structured process before treatment begins.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Review of lab reports — analyzing current and past creatinine, GFR, and related kidney function tests to understand the trend</li>
                <li>Detailed case history and dosha assessment — identifying lifestyle, dietary, and constitutional factors contributing to the elevation</li>
                <li>Customized herbal formulations — selected to support kidney filtration and reduce toxin accumulation, based on the individual case</li>
                <li>Diet and hydration guidance — a structured Pathya-Apathya plan aligned with the patient&apos;s protein, potassium, and sodium restrictions</li>
                <li>Lifestyle correction — addressing sleep, stress, and activity patterns that may be affecting kidney health</li>
                <li>Periodic lab monitoring — reassessing creatinine and related markers at intervals to track whether the treatment plan is working</li>
                <li>Coordination with your nephrologist — ensuring your Ayurvedic care plan does not conflict with ongoing medical treatment</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Herbs Traditionally Used to Support Creatinine Reduction
              </h2>

              <p className="mb-4 text-gray-700">
                These herbs are used in supervised formulations, adjusted to the patient&apos;s condition and current kidney function.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Punarnava (Boerhavia diffusa) — traditionally used to support fluid balance and kidney function</li>
                <li>Gokshura (Tribulus terrestris) — supportive for the urinary system and overall renal comfort</li>
                <li>Varuna (Crataeva nurvala) — used in classical formulations for urinary and kidney health</li>
                <li>Guduchi (Tinospora cordifolia) — traditionally valued for supporting the body&apos;s detoxification processes</li>
                <li>Rakt Chandan (Red Sandalwood) — occasionally used in supportive formulations for its traditional cooling and purifying properties</li>
                <li>Nishottar — used cautiously in select formulations for its traditional role in supporting elimination</li>
                <li>Shatavari (Asparagus racemosus) — used to support overall strength and nourishment during treatment</li>
              </ul>

              <p className="text-gray-700">
                These herbs are never prescribed as a standalone or self-administered remedy at Balprada. Inappropriate herbal use in patients with reduced kidney function can be harmful, so every formulation is decided only after clinical evaluation and report review.
              </p>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Dietary Guidance to Support Lower Creatinine Levels
              </h2>

              <p className="mb-4 text-gray-700">
                Diet is one of the most important factors in supporting creatinine management, and our recommendations are always aligned with your nephrologist&apos;s advice.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Following a controlled-protein diet, since excess protein intake can increase the workload on the kidneys</li>
                <li>Reducing sodium intake to help manage blood pressure and fluid balance</li>
                <li>Limiting or avoiding high-potassium and high-phosphorus foods when advised by your medical team</li>
                <li>Maintaining appropriate hydration as guided by your doctor, particularly important since both too little and too much fluid can be problematic</li>
                <li>Avoiding processed, canned, and preserved foods high in sodium and additives</li>
                <li>Choosing fresh, easily digestible seasonal vegetables within medically approved limits</li>
                <li>Avoiding red meat, alcohol, and excessive caffeine</li>
                <li>Including small amounts of healthy fats such as ghee, as advised, for sustained energy</li>
                <li>Eating smaller, more frequent meals to ease the digestive and metabolic load on the body</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Lifestyle Measures That Support Kidney Function
              </h2>

              <p className="mb-4 text-gray-700">
                Beyond diet and herbs, certain lifestyle habits play a meaningful supportive role.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Maintaining consistent, adequate sleep to support the body&apos;s natural repair processes</li>
                <li>Avoiding self-medication, especially over-the-counter painkillers, which can worsen kidney stress</li>
                <li>Managing stress through gentle practices such as breathing exercises, as tolerated</li>
                <li>Engaging in light, doctor-approved physical activity to support overall metabolic health</li>
                <li>Keeping blood pressure and blood sugar well controlled, since both directly affect kidney function and creatinine levels</li>
                <li>Attending scheduled follow-ups consistently, rather than only when symptoms appear</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Panchakarma and Creatinine Management: What&apos;s Appropriate
              </h2>

              <p className="mb-4 text-gray-700">
                Certain gentle Panchakarma-linked therapies may be considered as part of a supportive plan, though this is always individualized.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Aggressive detoxification procedures are generally avoided in patients with significantly reduced kidney function</li>
                <li>Any therapy is chosen only after reviewing the patient&apos;s current creatinine level, GFR, and overall stability</li>
                <li>Mild, closely monitored supportive therapies may be considered in stable patients, with physician approval</li>
                <li>Therapies involving significant fluid shifts are approached with particular caution</li>
                <li>This is never applied as a standard protocol — every decision is based on the individual patient&apos;s reports and condition</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Setting Realistic Expectations
              </h2>

              <p className="mb-4 text-gray-700">
                Honesty with patients and families is central to how we approach creatinine-related care.
              </p>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Ayurveda may support the body&apos;s natural processes, but it cannot guarantee a specific reduction in creatinine for every patient</li>
                <li>Results vary significantly depending on the underlying cause, stage of kidney disease, and how early treatment begins</li>
                <li>Ayurvedic supportive care should never replace prescribed nephrology treatment, dialysis, or medication</li>
                <li>Patients should continue all medical treatment and keep their nephrologist informed about any supportive Ayurvedic care they are undergoing</li>
                <li>We track progress through actual lab reports rather than assumptions, and we communicate results transparently at every stage</li>
              </ul>
            </div>

            <div className="mb-12">
              <h2 className="mb-4 font-serif text-3xl text-gray-900">
                Why Patients Choose Balprada Ayurvedic Hospital
              </h2>

              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-700">
                <li>Experienced Ayurvedic physicians with specific focus on kidney health and metabolic disorders</li>
                <li>Treatment plans built around actual lab reports and trends, not generic protocols</li>
                <li>In-house diagnostic facilities to help track creatinine and related markers over time</li>
                <li>Transparent communication about realistic outcomes and treatment timelines</li>
                <li>Encouraged coordination between our physicians and the patient&apos;s treating nephrologist</li>
                <li>A calm, structured environment for patients managing an often stressful health concern</li>
              </ul>
            </div>

            <div className="mb-12 rounded-2xl bg-[#F8F4EA] p-8 text-black">
              <h2 className="mb-4 font-serif text-3xl">
                Book a Consultation at Balprada
              </h2>

              <p className="mb-6 text-black">
                Patients with elevated creatinine can book a consultation at Balprada Ayurvedic Hospital &amp; Research Center in Moradabad. Our physicians review your latest and previous creatinine, GFR, and related kidney function reports before designing a personalized supportive care plan alongside your nephrologist&apos;s treatment.
              </p>

              <div className="mb-6 space-y-4">
                <div className="flex items-start gap-3">
                  <MapPin
                    size={20}
                    className="mt-1 shrink-0 text-black"
                  />

                  <div>
                    <p className="font-semibold">Main Branch</p>
                    <p className="text-black">
                      Mohalla Vijaynagar, Village Bhidwari, P.O. Guarau,
                      Tehsil Bilari, District Moradabad, Uttar Pradesh 244415
                    </p>
                  </div>
                </div>

                <div className="mt-4 flex items-start gap-3">
                  <MapPin
                    size={20}
                    className="mt-1 shrink-0 text-black"
                  />

                  <div>
                    <p className="font-semibold">Moradabad Branch</p>
                    <p className="text-black">
                      F-19, Sector-13, New Moradabad, Delhi Road,
                      Moradabad, Uttar Pradesh 244001
                    </p>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <Phone
                    size={20}
                    className="mt-1 shrink-0 text-black"
                  />

                  <div>
                    <p className="font-semibold">Contact Balprada</p>

                    <div className="flex items-center gap-3 text-black">
                      <a href="tel:9410447000" className="hover:underline">
                        9410447000
                      </a>

                      <span className="text-gray-400">|</span>

                      <a href="tel:8126364606" className="hover:underline">
                        8126364606
                      </a>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex flex-wrap gap-4">
                <Link href="/contact">
                  <button className="rounded-lg bg-white px-6 py-3 font-semibold text-blue-900 transition hover:bg-blue-50">
                    <Phone className="mr-2 inline" size={18} />
                    Contact Us
                  </button>
                </Link>

                <Link href="/treatments">
                  <button className="rounded-lg border-2 border-white px-6 py-3 font-semibold transition hover:bg-blue-800">
                    Explore Treatments
                  </button>
                </Link>
              </div>
            </div>

            <div className="mb-12">
              <h2 className="mb-6 font-serif text-3xl text-gray-900">
                Frequently Asked Questions
              </h2>

              <div className="space-y-5">
                {faqs.map((faq) => (
                  <div
                    key={faq.q}
                    className="rounded-lg border border-gray-200 p-5"
                  >
                    <h3 className="mb-2 font-semibold text-gray-900">
                      {faq.q}
                    </h3>

                    <p className="text-gray-700">{faq.a}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="order-2 w-full lg:w-[380px] xl:w-[420px]">
            <div className="space-y-6 lg:sticky lg:top-28">
              <LandingEnquiryForm />
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}